### PR TITLE
Facebook username Extraction from facebook profile link

### PR DESCRIPTION
**Pull request by m4hi2**
wrote a the function in a separate file.

### CODE REVIEW

**Comment by fazlerabby7** [comment]
1. It is not really necessary to check if the link is from group feed or not.
2. The function name should be something like get_facebook_username(facebook_profile_url)
3. The function is not working as expected.
```python
>>> import facebook
>>> username = facebook.is_facebook_link('https://www.facebook.com/fr070?fref=nf')
>>> print(username)
None
```

**Comment by m4hi2** [comment]
> It is not really necessary to check if the link is from group feed or not.
This program is only intended to be used in groups, right? If we don't match it that way it's possible to match with pages as well

> The function name should be something like get_facebook_username(facebook_profile_url)
Hmm, that's reasonable. I'll change it.

> The function is not working as expected.
Yes, It is working if you use it in ideal conditions. I don't think anyone will be typing links manually. When writing this I had a idea in mind and that being anyone using this will be using the "Copy Link Location" option available in modern browsers. In that case you'll have `web.facebook.com` instead of `www.facebook.com`. I can fix that also but at this point I really don't think it'll change anything.

**Comment by m4hi2** [comment]
This new commit solves the issues you raised last time. Hope this helps.

**Comment by fazlerabby7** [comment]
> It is not really necessary to check if the link is from group feed or not
> > This program is only intended to be used in groups, right? If we don't match it that way it's possible to match with pages as well

Yeah right. But how can you determine whether it's from group or not? By trailing `fref=nf/ufi`? Links from some other sources also have the same. That's why I have said it's not important. How about just ignoring the trailing parameters?

> The function is not working as expected.
> > Yes, It is working if you use it in ideal conditions. I don't think anyone will be typing links manually. When writing this I had a idea in mind and that being anyone using this will be using the "Copy Link Location" option available in modern browsers. In that case you'll have web.facebook.com instead of www.facebook.com. I can fix that also but at this point I really don't think it'll change anything.

If someone browses facebook from mobile broadband (as far I've noticed), he gets web.facebook.com, if from mobile, he gets (m/mobile/touch/mbasic/iphone/free).facebook.com. Otherwise it's www.facebook.com. I think we should include these in the regex.

And another thing, if the user doesn't have username, the profile url will look like `https://www.facebook.com/profile.php?id=100008225981344&fref=ufi`. We should have a mechanism to extract the profile id instead of username in that type of case. This thread might be helpful in that case http://stackoverflow.com/q/5205652.

Thanks for your hard work :)

**Comment by m4hi2** [comment]
> Yeah right. But how can you determine whether it's from group or not? By trailing fref=nf/ufi? Links from some other sources also have the same. That's why I have said it's not important. How about just ignoring the trailing parameters?

If I check that way I can easily snatch the username from the link with regEx groups. But if I remove that last part the job will be difficult and more resource consuming at least I don't know another way to do this without loops. As these extra checks don't hurt the expected results, I'll vote to keep those as they help making the code run faster. :smile: 

I've the other part ready. No filling like doing another rebase. So tell me your thoughts on this and I'll push everything at once :smiling_imp:

**Comment by m4hi2** [comment]
> Yeah right. But how can you determine whether it's from group or not? By trailing fref=nf/ufi? Links from some other sources also have the same. That's why I have said it's not important. How about just ignoring the trailing parameters?

If you want I can remove the trailing params but let me point out the problem first. :smile: I'm using regex group to extract the user name. We both don't know what combinations the user name can be and how long it is. So I found it easier to have the user name surrounded so that I can extract it with ease. In current approach if I delete the trailing params I'll have to run a loop like [last commit](https://github.com/fazlerabby7/group_warning/pull/1/commits/7df47083be4e90bfd1b38200412855ae6b5c2609#diff-30dd34032e75f1394989723d75fefd86R20) and it'll take more time to execute. As these params really don't affect the usability, I'll vote to keep these. If they pose a threat in the future I'll be more than happy to replace them with other methods. :smile: 

>  If someone browses facebook from mobile broadband (as far I've noticed), he gets web.facebook.com, if from mobile, he gets (m/mobile/touch/mbasic/iphone/free).facebook.com. Otherwise it's www.facebook.com. I think we should include these in the regex.

This issue is already fixed. Take a look [here](https://github.com/fazlerabby7/group_warning/pull/1/commits/9816d04340d474b17ca875b10360c025b4e61afb#diff-30dd34032e75f1394989723d75fefd86R11)

> And another thing, if the user doesn't have username, the profile url will look like https://www.facebook.com/profile.php?id=100008225981344&fref=ufi. We should have a mechanism to extract the profile id instead of username in that type of case. This thread might be helpful in that case http://stackoverflow.com/q/5205652.

I really like writing my own regex because I know everything when I write them, I've written `(http|https):\/\/(web\.|www\.)facebook\.com\/profile\.php\?id=([0-9]{15})` based on your provided example link. 

If you want, I can change how `get_facebook_username()` works and remove those trailing params but at this point I really don't feel the appeal behind that. Let me know what do you think. I've the code ready, I'll push everything if you feel OK. :+1:

**Comment by fazlerabby7** [comment]
Now that's a valid reason to keep the trailing params (not for determining group feed). So this part is fine.

> If someone browses facebook from mobile broadband (as far I've noticed), he gets web.facebook.com, if from mobile, he gets (m/mobile/touch/mbasic/iphone/free).facebook.com. Otherwise it's www.facebook.com. I think we should include these in the regex.
> > This issue is already fixed. Take a look here

Please add these too (m/mobile/touch/mbasic/iphone/free).

> I really like writing my own regex because I know everything when I write them, I've written (http|https):\/\/(web\.|www\.)facebook\.com\/profile\.php\?id=([0-9]{15}) based on your provided example link.

I thought you would like to use the same regex instance to get the username or the id, that was why I shared the SO thread. But if you make it work in another way, that's absolutely fine.

Waiting to get the final code.

**Comment by m4hi2** [comment]
> I thought you would like to use the same regex instance to get the username or the id, that was why I shared the SO thread. But if you make it work in another way, that's absolutely fine.

It's okay bhai. I've used the same structure of regex as I used before and I really don't think we'll to use that much of complicated regex anyway. 

This should work. I'll be more than happy to fix anything you point out. :smile:

**Comment by fazlerabby7** [comment]
> This should work. I'll be more than happy to fix anything you point out.

Really nice to hear (see :stuck_out_tongue:) :smiley:


Just one more thing. Make only one function, suppose get_fb_username_or_id(fb_profile_url). If username is found, return it. Otherwise check for profile id and return it.

**Comment by m4hi2** [comment]
> Just one more thing. Make only one function, suppose get_fb_username_or_id(fb_profile_url). If username is found, return it. Otherwise check for profile id and return it.

I thought as these are very different thing and many user may opt to have a different user name in near future, it'll be easier to add more functionality down the line if we have two functions. :smile: Think about it, I'll have another version ready if you say we need to merge these functions :+1:

**Comment by fazlerabby7** [comment]
As we are storing username or profile id at the same column for keeping the things simple, I think merging these two function will be convenient.

**Comment by fazlerabby7** [comment]
Thanks for your effort @m4hi2. I have done some refactoring [here](https://github.com/fazlerabby7/group_warning/commit/15664ce00df785e1e17c0133ed380982e04487b2).

**Pull request merged**
